### ISSUE TITLE
no-unused: Doesn't recognize JSX fragments

### ISSUE THREAD

**Issue by johnsoft** [ajafff/tslint-consistent-codestyle#87]
```tsx
import React from 'react';

export function Placeholder() {
  return <>placeholder</>;
}
```

This package reports that import 'React' is unused, but it is used implicitly to create the fragment.

**Comment by ajafff** [comment]
This rule currently doesn't use TypeScript's TypeChecker. Therefore is doesn't know what JSX factory you are using.
So this is a design limitation until I find the time to rewrite the rule.
And it is not limited to JSX fragments. This issue is present for all JSX elements.

For the time being you can use the option `"ignore-imports"`
